name: Harbour bins, dlls, curl, ssl 64b MinGW 10.2

on:
  [workflow_dispatch]
  
jobs:
  build:
    runs-on: windows-latest

    if: github.actor == github.event.repository.owner.login

    steps:
    - name: Checkout harbour/core repo
      uses: actions/checkout@v2
      with:
       repository: harbour/core
       path: harbour

    - name: Install dependencies
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-8.0.0-r8/winlibs-x86_64-posix-seh-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r8.zip', 'C:\temp\mingw.zip')
        Expand-Archive -LiteralPath C:\temp\mingw.zip -DestinationPath C:\mingw -Force
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
        Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
        Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/acesdk.zip', 'C:\temp\acesdk.zip')
        Expand-Archive -LiteralPath C:\temp\acesdk.zip -DestinationPath C:\acesdk -Force
        (new-object System.Net.WebClient).DownloadFile('https://curl.se/windows/dl-7.76.0/curl-7.76.0-win64-mingw.zip', 'C:\temp\curl776.zip')
        Expand-Archive -LiteralPath C:\temp\curl776.zip -DestinationPath C:\curl776 -Force
        (new-object System.Net.WebClient).DownloadFile('https://curl.se/windows/dl-7.76.0/openssl-1.1.1k-win64-mingw.zip', 'C:\temp\openssl_111.zip')
        Expand-Archive -LiteralPath C:\temp\openssl_111.zip -DestinationPath C:\openssl_111 -Force
    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_PARTS=all
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=c:\openssl_111\openssl-1.1.1k-win64-mingw\include
        set HB_WITH_CURL=c:\curl776\curl-7.76.0-win64-mingw\include
        set HB_WITH_ADS=c:\acesdk
        set HB_STATIC_OPENSSL=yes
        set HB_OPENSSL_STATIC=yes
        set HB_STATIC_CURL=yes
        set HB_COMPILER=mingw64
        set HB_BUILD_CONTRIB_DYN=yes
        set HB_BUILD_DYN=yes
        set HB_WITH_LIBHARU=c:\harbour\contrib\hbhpdf
        :: set path=c:\mingw32\mingw32\bin;c:\openssl\bin;c:\curl;%path%
        set HB_USER_CFLAGS=-cflag=-DHB_OPENSSL_STATIC
        set path=c:\mingw\mingw64\bin;c:\openssl_111\openssl-1.1.1k-win64-mingw\bin;c:\curl776\curl-7.76.0-win64-mingw\bin;%path%
        win-make.exe
    - name: Create output folders
      shell: cmd
      run: |
        mkdir output
        
        echo adding curl 7.76 to harbour binaries
        robocopy C:\curl776\curl-7.76.0-win64-mingw\ output\curl_776 /E
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        echo adding curl ErrorLevel = %ERRORLEVEL%
        
        echo adding openssl 1.1.1 to harbour binaries
        robocopy C:\openssl_111\openssl-1.1.1k-win64-mingw\ output\openssl_111 /E
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        echo adding openssl ErrorLevel = %ERRORLEVEL%
        
        robocopy harbour\ output /E
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        echo %ERRORLEVEL%
        echo creating harbour binaries ErrorLevel = %ERRORLEVEL%
        
        rmdir output\.git /S /Q
        del output\.git* /S /Q
        del output\os2-make.exe /S /Q
        del output\dos-make.exe /S /Q
        del output\win-make.exe /S /Q
        del output\.travis.yml /S /Q
        rmdir output\package /S /Q
        rmdir output\debian /S /Q
        rmdir output\config /S /Q
        rmdir output\addons /S /Q
        rmdir output\lib\win\mingw64\.hbmk /S /Q
        echo clean objects
        move output\bin\win\mingw64\*.* output\bin
        rmdir output\bin\win /S /Q
        echo mover harbour binaries ErrorLevel = %ERRORLEVEL%
        rmdir output\src\rtl\gtwin\obj /S /Q
        rmdir output\src\rtl\gtwvt\obj /S /Q
        rmdir output\src\rtl\gtstd\obj /S /Q
        rmdir output\src\rdd\usrrdd\rdds\obj /S /Q
        echo clean objects 1
        :: move output\lib\3rd\win\mingw64\libunicow*.* output\lib\win\mingw
        rmdir output\lib\3rd /S /Q
        echo clean objects 1-2
        rmdir output\src\vm\obj /S /Q
        echo clean objects 2
        rmdir output\src\rtl\obj /S /Q
        rmdir output\src\rdd\obj /S /Q
        echo clean objects 3
        rmdir output\src\pp\obj /S /Q
        rmdir output\src\nortl\obj /S /Q
        echo clean objects 4
        rmdir output\src\main\obj /S /Q
        rmdir output\src\macro\obj /S /Q
        echo clean objects 5
        rmdir output\src\lang\obj /S /Q
        rmdir output\src\hbextern\obj /S /Q
        echo clean objects 6
        :: rmdir output\src\dynlib\obj /S /Q
        rmdir output\src\debug\obj /S /Q
        echo clean objects 7
        rmdir output\src\compiler\obj /S /Q
        rmdir output\src\common\obj /S /Q
        echo clean objects 8
        rmdir output\src\codepage\obj /S /Q
        rmdir output\src\3rd\zlib\obj /S /Q
        echo clean objects 9
        rmdir output\src\3rd\tiff\obj /S /Q
        rmdir output\src\3rd\png\obj /S /Q
        echo clean objects 10
        rmdir output\src\3rd\pcre\obj /S /Q
        rmdir output\src\3rd\jpeg\obj /S /Q
        echo clean objects 11
        rmdir output\src\rdd\usrrdd\obj /S /Q
        rmdir output\src\rdd\nulsys\obj /S /Q
        echo clean objects 12
        rmdir output\src\rdd\hsx\obj /S /Q
        rmdir output\src\rdd\hbsix\obj /S /Q
        echo clean objects 13
        rmdir output\src\rdd\dbfntx\obj /S /Q
        rmdir output\src\rdd\dbfnsx\obj /S /Q
        echo clean objects 14
        rmdir output\src\rdd\dbffpt\obj /S /Q
        rmdir output\src\rdd\dbfcdx\obj /S /Q
        echo clean objects 15
        rmdir output\src\vm\vmmt\obj /S /Q
        rmdir output\src\vm\mainwin\obj /S /Q
        echo clean objects 16
        rmdir output\src\vm\mainstd\obj /S /Q
        rmdir output\src\vm\maindllp\obj /S /Q
        echo clean objects 17
        rmdir output\src\vm\maindllh\obj /S /Q
        rmdir output\utils\hbtest\obj /S /Q
        echo clean objects 18
        rmdir output\utils\hbmk2\obj /S /Q
        rmdir output\utils\hbi18n\obj /S /Q
        
        echo end clean objects
        
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYYMMDD-HH

    - name: Upload Harbour to artifact
      env:
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: hb32_curl_ssl_mgw102_64b_${{ env.F_TIME }}
       path: output
